#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
export GOPATH="${HOME}/go"
export PATH="/apollo/env/SDETools/bin:$PATH:$GOPATH/bin"

bindkey '^R' history-incremental-search-backward

KEYTIMEOUT=1

alias vim="nvim"
alias v="vim"
# allow neovim to change cursor shape in different modes
export NVIM_TUI_ENABLE_CURSOR_SHAPE=1

vimgitshow() { git show "$1" | vim - "+set filetype=${1##*.}"; }
